headers = {
    'Accept': '*/*',
    'Onboarding': '2',
    'TGPlatform': 'ios',
    'Locale': 'ru',
    'Accept-Language': 'ru',
    'Origin': 'https://qlyuker.io',
    'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X)',
    'Referer': 'https://qlyuker.io/upgrades',
    'Content-Type': 'application/json',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    'Connection': 'keep-alive',
}